apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.fullname }}     #i27-eureka-dev
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas.default }}
  selector: 
    matchLabels: 
      name: {{ .Values.name }}     #i27-eureka-dev
  template:
    metadata:
      labels: 
        name: {{ .Values.name }}  #i27-eureka-dev
    spec:
      containers:
        - image: "{{ .Values.image.name }}:{{ .Values.image.tag }}" # registryname/reponame/appname:tagname
          name: {{ .Values.name }}