apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.fullname }}   #i27-eureka-dev-svc
spec:
  selector:
    name: {{ .Values.name }}
  type: NodePort # ClusterIP, NodePort, LoadBalancer
  ports:
  - protocol: TCP
    port : 80 # This is the service port
    targetPort: {{ .Values.targetport }}